[package]
name = "bevy_splash_screen"
version = "0.0.0"
edition = "2021"
license = "MIT OR APACHE-2.0"
repository = "https://github.com/SergioRibera/bevy_splash_screen"

[dependencies]
bevy = "0.10.1"
bevy_tweening = "0.7.0"

[patch.crates-io]
bevy_tweening = { git = "https://github.com/sibsibsib/bevy_tweening", branch = "mirrored_repeat_fix" }
