[package]
name = "bevy_splash_screen"
description = "A plugin for bevy which allows you to create screens to show the brands and development teams behind your amazing game"
version = "0.4.2"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SergioRibera/bevy_splash_screen"
keywords = ["gamedev", "ui", "bevy"]

[dependencies]
bevy = "0.11"
bevy_tweening = { git = "https://github.com/djeedai/bevy_tweening", rev = "cad68be96e492482cb6dfd395f07d4bc73d353bf" }

[patch."https://github.com/djeedai/bevy_tweening"]
bevy_tweening = { git = "https://github.com/SergioRibera/bevy_tweening", branch = "infinite_mirrored" }
