[package]
name = "bevy_splash_screen"
description = "A plugin for bevy which allows you to create screens to show the brands and development teams behind your amazing game"
version = "0.0.0"
edition = "2021"
license = "MIT OR APACHE-2.0"
repository = "https://github.com/SergioRibera/bevy_splash_screen"
keywords = ["gamedev", "ui", "bevy"]

[dependencies]
bevy = "0.10.1"
bevy_tweening = "0.7.0"

[patch.crates-io]
bevy_tweening = { git = "https://github.com/sibsibsib/bevy_tweening", branch = "mirrored_repeat_fix" }
