[package]
name = "bevy_splash_screen"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"
bevy_tweening = "0.7.0"

[patch.crates-io]
bevy_tweening = { git = "https://github.com/sibsibsib/bevy_tweening", branch = "mirrored_repeat_fix" }
